module.exports = {
  users: [
    {
      id: 2244994945,
      id_str: "2244994945",
      name: "Twitter Dev",
      screen_name: "TwitterDev",
      location: "Internet",
      description:
        "Your official source for Twitter Platform news, updates & events. Need technical help? Visit https://t.co/mGHnxZU8c1 ⌨️ #TapIntoTwitter",
      url: "https://t.co/FGl7VOULyL",
      entities: {
        url: {
          urls: [
            {
              url: "https://t.co/FGl7VOULyL",
              expanded_url: "https://developer.twitter.com/",
              display_url: "developer.twitter.com",
              indices: [0, 23],
            },
          ],
        },
        description: {
          urls: [
            {
              url: "https://t.co/mGHnxZU8c1",
              expanded_url: "https://twittercommunity.com/",
              display_url: "twittercommunity.com",
              indices: [93, 116],
            },
          ],
        },
      },
      protected: false,
      followers_count: 502084,
      friends_count: 1472,
      listed_count: 1514,
      created_at: "Sat Dec 14 04:35:55 +0000 2013",
      favourites_count: 2203,
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      verified: true,
      statuses_count: 3393,
      lang: "en",
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: null,
      profile_background_color: "null",
      profile_background_image_url: "null",
      profile_background_image_url_https: "null",
      profile_background_tile: null,
      profile_image_url: "null",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/880136122604507136/xHrnqf1T_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/2244994945/1498675817",
      profile_link_color: "null",
      profile_sidebar_border_color: "null",
      profile_sidebar_fill_color: "null",
      profile_text_color: "null",
      profile_use_background_image: false,
      has_extended_profile: null,
      default_profile: false,
      default_profile_image: false,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: "null",
    },
    {
      id: 6253282,
      id_str: "6253282",
      name: "Twitter API",
      screen_name: "TwitterAPI",
      location: "San Francisco, CA",
      description:
        "The Real Twitter API. Tweets about API changes, service issues and our Developer Platform. Don't get an answer? It's on my website.",
      url: "https://t.co/8IkCzCDr19",
      entities: {
        url: {
          urls: [
            {
              url: "https://t.co/8IkCzCDr19",
              expanded_url: "https://developer.twitter.com",
              display_url: "developer.twitter.com",
              indices: [0, 23],
            },
          ],
        },
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 502084,
      friends_count: 1472,
      listed_count: 1514,
      created_at: "Sat Dec 14 04:35:55 +0000 2013",
      favourites_count: 2203,
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      verified: true,
      statuses_count: 3393,
      lang: "en",
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: null,
      profile_background_color: "null",
      profile_background_image_url: "null",
      profile_background_image_url_https: "null",
      profile_background_tile: null,
      profile_image_url: "null",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/880136122604507136/xHrnqf1T_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/2244994945/1498675817",
      profile_link_color: "null",
      profile_sidebar_border_color: "null",
      profile_sidebar_fill_color: "null",
      profile_text_color: "null",
      profile_use_background_image: false,
      has_extended_profile: null,
      default_profile: false,
      default_profile_image: false,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: "null",
    },
  ],
  next_cursor: 0,
  next_cursor_str: "0",
  previous_cursor: 0,
  previous_cursor_str: "0",
  total_count: null,
}
